services:
  web:
    build:
      context: .
      dockerfile: ./apps/web-app/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '4200:4200'
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
