FROM node:20.18.0-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the project files
COPY . .

# Expose the React development server port (3000)
EXPOSE 4200

CMD ["npx", "nx", "serve", "web-app"]
