FROM node:20.18.0-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
# COPY tools/scripts/postinstall.sh ./tools/scripts/postinstall.sh
RUN npm install --legacy-peer-deps

# Copy the project files
COPY . .

# Expose the React development server port (3000)
EXPOSE 4200

CMD ["npx", "nx", "serve", "web-app"]
