# Use an official Node.js image
FROM alpine:3.20

ENV NODE_VERSION 20.18.0

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock ./
RUN npm install

# Copy the project files
COPY . .

# Expose the React development server port (3000)
EXPOSE 3000

# Start the React app in development mode
CMD ["npm", "nx", "serve", "web"]