export enum TagItemColorEnum {
  BUG = 'bugTheme',
  DARK = 'darkTheme',
  DRAGON = 'dragonTheme',
  ELECTRIC = 'electricTheme',
  FAIRY = 'fairyTheme',
  FIGHTING = 'fightingTheme',
  FIRE = 'fireTheme',
  FLYING = 'flyingTheme',
  GHOST = 'ghostTheme',
  GRASS = 'grassTheme',
  GROUND = 'groundTheme',
  ICE = 'iceTheme',
  NORMAL = 'normalTheme',
  POISON = 'poisonTheme',
  PSYCHIC = 'psychicTheme',
  ROCK = 'rockTheme',
  STEEL = 'steelTheme',
  WATER = 'waterTheme',
}
