FROM node:20.18.0-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy the project files
COPY . .

# Expose the Node.js server port
EXPOSE 3333

# Start the server with nodemon for hot reloading
CMD npx nx reset && npx nx run api:serve --configuration=development
